import Providers from "@/components/providers/Providers";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import NextTopLoader from 'nextjs-toploader';
import { inter } from "../font";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {


  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <head>
        <meta name="theme-color" content="#fff" />

      </head>
      <body className={cn(inter.className, "min-h-dvh text-base")}>
        <NextTopLoader
          // color="bla"
          showSpinner={false}
          zIndex={1000}
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
