import "@/styles/globals.css";
import Providers from "@/components/providers/Providers"
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import NextTopLoader from 'nextjs-toploader';
import { TRPCReactProvider } from "@/server/trpc/react";
import { cn } from "@/lib/utils";
import { inter } from "../font";
import { initCronsIntercepter } from "@/server/api/root";
import { env } from "@/env";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {

  if (env.NODE_ENV_2 === "development") {
    await initCronsIntercepter("test-api")
  }

  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <head>
        <meta name="theme-color" content="#fff" />

      </head>
      <body className={cn(inter.className, "min-h-dvh text-base")}>
        <NextTopLoader
          // color="bla"
          showSpinner={false}
          zIndex={1000}
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
