import "@/styles/globals.css";
import Providers from "@/components/providers/Providers"
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import NextTopLoader from 'nextjs-toploader';
import { TRPCReactProvider } from "@/server/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="min-h-dvh">
        <NextTopLoader
          // color="bla"
          showSpinner={false}
        />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
